
version: "3"
services:
  php-fpm:
    build:
      context: ..
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ../www:/var/www

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
#      - ../www:/var/www
      - php-fpm:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  php-fpm:
