version: "3"
services:
  php-fpm:
    build:
      context: ..
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - data:/var/www
      - web:/etc/nginx/conf.d

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - data:/var/www
      - web:/etc/nginx/conf.d

volumes:
  data:
  web:
