version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../www:/var/www
